### ISSUE TITLE
Traders giving me more than 1 free pistols 

### ISSUE THREAD

**Issue by kegy21** [Kenan2000/BL9#11]
the traders on the castle are giving me free pistols even do i already claimed one is this intended?

**Comment by Kenan2000** [comment]
> the traders on the castle are giving me free pistols even do i already claimed one is this intended?

Awesome to see you playing BL9, it's intended just in case one looses the pistol, it's basically the default weapon, currently you can exploit it but I doubt that it would be that much fun, it is intended that you just acquire it once at the beginning and if you somehow drop it or break it, you can get back to the merchant and get the Tier 1 pistol whenever you want to since it deals little damage initially as well

**Comment by kegy21** [comment]
I see thank you for replying!
